version: '3.1'
services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=wachtwoord
      - MYSQL_DATABASE=database
    networks:
      - database
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=wachtwoord
    restart: always
    ports:
      - 8080:80
    networks:
      - database
    links:
      - db
networks:
  database: